### ISSUE TITLE
[BUG] Check for updates error

### ISSUE THREAD

**Issue by joshcangit** [jonjomckay/fritter#565] opened 2022-11-15 06:35 UTC
> Please make sure you've tried the [latest version](https://github.com/jonjomckay/fritter/releases) of Fritter first, as the F-Droid version is sometimes out of date!

**Describe the bug**
Fritter shows error when checking for updates.

**To Reproduce**
1. Go to _Settings_
2. Click on _Check for updates_
3. See error when opening Fritter

**Screenshots**
![Screenshot_20221115-142630_Fritter.png](https://user-images.githubusercontent.com/33022160/201843919-5c19b5c7-a018-4114-998e-6d15f08bc1e8.png)

**Device**
Fritter:
3.0.0-beta4 (20220923)
Android version:
12
Kernel build information:
Linux localhost 4.14.113-24706840 #1 SMP PREEMPT Thu Jul 21 14:53:58 KST 2022 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-G973F

**Comment by jonjomckay** [comment] 2022-11-26 12:08
This was caused by an outage in the update checking script. It should be fixed now!

**Closed by jonjomckay** 2022-11-26 12:08 UTC
Labels: bug

**Comment by joshcangit** [comment] 2022-11-26 14:10
Oh, it was checking for the latest release.
I'm using the latest pre-release.
