### ISSUE TITLE
[BUG] Unable to see feed or search for a user 

### ISSUE THREAD

**Issue by Arthurvip** [jonjomckay/fritter#677] opened 2023-04-26 07:22 UTC
@jonjomckay 
![Screenshot_20230426-001606_Fritter](https://user-images.githubusercontent.com/131853601/234500152-9156b057-64cf-4bf4-9b89-48753926daff.png)

**Comment by TheHCJ** [comment] 2023-04-26 14:00
Duplicate #668

**Comment by jonjomckay** [comment] 2023-04-29 12:32
Closing as a duplicate of #668

**Closed by jonjomckay** 2023-04-29 12:32 UTC
Labels: bug
