### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by rzasharifi** [jonjomckay/fritter#673] opened 2023-04-25 14:28 UTC
> Please make sure you've tried the [latest version]
v3.0.0-beta6+300000772

**Describe the bug**
nothing shows in the feed, however, I saved some and if I click on there profile, I can watch their contents.

**To Reproduce**
3. See error

**Screenshots**
![Screenshot_2023-04-25-17-51-41-732_com jonjomckay fritter](https://user-images.githubusercontent.com/64254187/234308355-79ef680d-2bb3-44fa-9277-a18270bafb43.jpg

redmi note 11, Android 12, Italy, english and Fritter version. Please supply the actual
version of Fritter being used, and **do not** just write "latest version" or similar, as this
changes constantly.

**Comment by jonjomckay** [comment] 2023-04-29 12:33
Closing as a duplicate of #668

**Closed by jonjomckay** 2023-04-29 12:33 UTC
Labels: bug
