### ISSUE TITLE
[BUG] Database corrupt or something

### ISSUE THREAD

**Issue by candiesdoodle** [jonjomckay/fritter#170] opened 2021-06-19 16:08 UTC
**Describe the bug**
When opening the app, shown this error message. subscription lists are gone. THough i can still look at trends and click and go to the feed.

**To Reproduce**
1. open the app
2. shown this error

**Screenshots**
attached

**Device**
v 2.10. v 2.11 - both had same issue
its Asus ROG 2 - Android 10
![photo1624118759](https://user-images.githubusercontent.com/20420013/122648391-a43fd880-d118-11eb-9832-d5c2115ccf53.jpeg)

**Comment by candiesdoodle** [comment] 2021-06-19 16:09
FWIW, already tried resetting the app by clearing the app storage.

**Comment by DocSniper** [comment] 2021-06-19 16:49
This appears to be a duplicate of #167

**Comment by candiesdoodle** [comment] 2021-06-19 18:18
Error message seems same, yes

**Comment by jonjomckay** [comment] 2021-06-19 18:38
I _think_ I've fixed this. I'm not able to reproduce it on my devices, as I think it's something handled differently in the different versions of SQLite bundled with Android, but I've made an educated guess based on the errors reported to Sentry. Please re-open if v2.11.2 doesn't solve the problem!

**Closed by jonjomckay** 2021-06-19 18:38 UTC
Labels: bug

**Comment by candiesdoodle** [comment] 2021-06-19 18:53
Solved in v 2.11.2
Thanks

**Comment by wongfeihung1984** [comment] 2021-06-21 01:49
I don't know why but my galaxy 9 refuses to install v2.11.2....I can download it and hit install, but after some times I get a message saying "application not installed".....

**Comment by jonjomckay** [comment] 2021-06-21 17:02
@wongfeihung1984 if you didn't already, you'll need to uninstall the F-Droid version before installing the GitHub version - they are signed with different keys, so one can't be upgraded to the other (and Android doesn't give a very useful error message for it 😢).

Don't forget to export your subscriptions before uninstalling though!
