### ISSUE TITLE
[BUG] Tweets not loading after updating to v2.16.0

### ISSUE THREAD

**Issue by desertproject** [jonjomckay/fritter#313] opened 2022-01-18 16:27 UTC
**Describe the bug**
After updating to v2.16.0 no tweets are loading. The main feed and group feeds shows an error: `Null check operator used on a null value`. Also, individual profiles simply do not show anything.

**Device**
Device: LG-H870S
Android: 8.0.0

**Comment by tswistak** [comment] 2022-01-18 21:28
I also have this on OnePlus 8 Pro (Android 11)

**Comment by jonjomckay** [comment] 2022-01-18 22:57
That's not great... I can't reproduce it with an existing or new installation unfortunately.

Is there any more information with the error message? Or a stack trace?

Also, are you able to temporarily enable Sentry (in the settings) so that a crash dump is submitted? I've checked there and nothing has been reported yet.

**Comment by jonjomckay** [comment] 2022-01-18 23:14
I think I've fixed this? Thanks to whoever submitted the error report to Sentry!

If you could check the v2.16.

**Comment by desertproject** [comment] 2022-01-19 00:44
> If you could check the v2.16.1 release once it's built, and confirm, that would be ace.

Now v2.16.1 does not show the error, only a empty screen instead of tweets. I have enabled Sentry and a report was sent.

**Comment by tswistak** [comment] 2022-01-19 07:07
Same as above on v2.16.1. Sent stack trace to Sentry.

**Comment by jonjomckay** [comment] 2022-01-19 11:51
This should be fixed now. Some tweets seem to be coming through for you with no creation date, which I didn't realise was possible. I still haven't seen any on my end, so I had to simulate the scenario.

Please re-open this if it's _still_ not working in v2.16.2!

**Comment by tswistak** [comment] 2022-01-19 11:58
There's still some exception, I've sent it to Sentry. However, now I can see tweets instead of an empty screen.

**Comment by desertproject** [comment] 2022-01-20 15:19
> This should be fixed now. Some tweets seem to be coming through for you with no creation date

I'm not sure if it's related but now I've noticed that there's no more info about date/hour in tweets like this screenshot taken from README.md (see "20 hour ago")

![](https://raw.githubusercontent.com/jonjomckay/fritter/master/fastlane/metadata/android/en-US/images/phoneScreenshots/3.jpg)

**Comment by jonjomckay** [comment] 2022-01-20 15:29
@desertproject yes, that's related - the creation date comes back as `null`, which causes the error, so Fritter has no data to display there.

To everyone affected in this thread, is your device using an non-English locale? I may have a theory, but I'll need confirmation on it!

**Comment by desertproject** [comment] 2022-01-20 15:36
> is your device using an non-English locale?

Yes, that's my case.

**Comment by jonjomckay** [comment] 2022-01-20 17:24
Thanks @desertproject and @tswistak!

So, I've figured out what this is. The library Fritter uses to parse the data coming back from Twitter's API into Dart objects assumes an `en_US` locale, and ends up returning `null` under any other locales.

I've submitted a PR to fix this in the library here: https://github.com/robertodoering/twitter_api/pull/18

**Comment by jonjomckay** [comment] 2022-01-23 17:32
I've just released v2.16.3, which _should_ fix this once and for all! Please re-open if this is still an issue after updating.

**Closed by jonjomckay** 2022-01-23 17:32 UTC
Labels: bug

**Comment by tswistak** [comment] 2022-01-23 17:37
@jonjomckay Dates are working, but now images in tweets and profile images won't load. Also, there is some exception after opening profile - I've sent it to Sentry. However, I don't know if it's still related to this issue...
