### ISSUE TITLE
[REQ] Text size adjustment ?

### ISSUE THREAD

**Issue by Mrnofish** [jonjomckay/fritter#676] opened 2023-04-26 06:37 UTC
**Describe the problem that needs solving**
After upgrading to 13, I am sad to realize Android is becoming ever more Apple-like in making sure we have large screens devoted to displaying even larger swaths of ~~useless~~sacred blank space.

The only way to combat this pernicious and concerning drift towards one-mouse-button land, is to tweak UI Size in the Android Settings, as the eggheads at Big G still haven't figured out yet that lusers shouldn't have access to sliders, but only big, colored, reassuring switches like "Think different" and "Think MORE Different (Premium $29.99/mo subscription required)".

In Fritter unfortunately this does cause text to shrink a little more than most other apps, IME.

**Describe the solution you'd like**
Even though this might trigger a ferocious and violent backlash from Minimalism Fundamentalists, I would love a text size adjustment in the settings, so that I can select a text size that is comfortable to me.

In future versions of Android, AI will make sure to analyze as much mined user data as possible and adjust text size automagically and on the fly, however the same AI will make sure we're all jobless and then wiped out from the face of Earth, so let's live a little while we can!

**Comment by jonjomckay** [comment] 2023-04-29 14:34
Closing as a duplicate of #279

**Closed by jonjomckay** 2023-04-29 14:34 UTC
Labels: enhancement
