### ISSUE TITLE
Categories for Saved Tweets [REQ] 

### ISSUE THREAD

**Issue by albaati** [jonjomckay/fritter#655] opened 2023-03-26 11:30 UTC
**Over the time, the saved tweets might be quite alot as they are gathered from accounts with diverse backgrounds and contexts.**

Would be nice if there a way to categorizing them, by creating folders/categories/branches  and even sub-categories (tree-style).

**Comment by jonjomckay** [comment] 2023-04-29 14:36
Closing as a duplicate of #169

**Closed by jonjomckay** 2023-04-29 14:36 UTC
Labels: enhancement
