### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Twig6943** [jonjomckay/fritter#705] opened 2023-05-08 22:44 UTC
A timeline where the latest tweets of the people you follow are shown I mean it should be possible.

**Comment by akawama** [comment] 2023-05-09 04:50
Now that Twitter has closed its API for feed, web scraping perhaps?

**Comment by ctntt** [comment] 2023-05-10 00:58
You (@Twig6943) accidentally opened the same issue twice. This is a duplicate of https://github.com/jonjomckay/fritter/issues/704.

**Comment by jonjomckay** [comment] 2023-05-10 22:32
This was the feed, which has recently been removed due to constant breakage on Twitter's end, and because I don't want to continue the problems that maintaining and using it cause: https://github.com/jonjomckay/fritter/issues/668#issuecomment-1538230835

**Closed by jonjomckay** 2023-05-10 22:32 UTC

**Comment by Twig6943** [comment] 2023-05-11 08:35
I mean isn't it possible without the twitter api? Cant you make the app itself get the latest tweets of the people you folow.

**Comment by ctntt** [comment] 2023-05-11 10:57
It is possible but jonjomckay already explained in detail why it won't be implemented in fritter https://github.com/jonjomckay/fritter/discussions/699.
Also there is already a fork which includes this feature https://github.com/TheHCJ/Quacker.

**Comment by Twig6943** [comment] 2023-05-11 15:36
@ctntt Thank you so much for the recommendation have a nice day.
