### ISSUE TITLE
[Feature Request] Back to Top by Tapping the Feed icon

### ISSUE THREAD

**Issue by alphanerdgen** [jonjomckay/fritter#159] opened 2021-06-15 07:01 UTC
It'd be nice to have the option to go back all the way to the top of the feed by simply tapping (or double tapping) the Feed icon.

Version: 2.9.0

**Comment by RequestPrivacy** [comment] 2021-06-19 08:10
I think this is a duplicate of #78 and maybe instead of "scrolling up" a simple refresh as proposed in #100 has the benefit of also receiving the newest tweets?

**Comment by jonjomckay** [comment] 2021-07-19 21:33
Closing as a duplicate of #78.

**Closed by jonjomckay** 2021-07-19 21:33 UTC
