### ISSUE TITLE
[BUG] comments fail to load

### ISSUE THREAD

**Issue by fusionneur** [jonjomckay/fritter#419] opened 2022-07-27 20:21 UTC
![315f50fdda294747480d063c82ddf2831e25eda57b426194900b7116684bafeb](https://user-images.githubusercontent.com/7840350/181365006-450a309b-8f16-479c-943a-98bf1c101b20.jpg)

**Comment by geominorai** [comment] 2022-08-02 07:44
Duplicate of issue #356 but unfortunately there have been no new releases despite it being fixed 5 months ago.

**Comment by goat-oss** [comment] 2022-08-14 07:49
v2.16.3 android 12.

**Comment by kvnvallis** [comment] 2022-08-21 20:02
Also happens on v3.0.0-beta1

**Comment by jonjomckay** [comment] 2022-08-21 20:48
Please could someone in the thread provide a link to a tweet or thread that reproduces this error? I was seeing this error on threads that contained deleted tweets, which is fixed now, but I need a bit of help finding what's causing it for you all.

**Comment by geominorai** [comment] 2022-08-21 21:04
I have a few examples in #356.

**Comment by jonjomckay** [comment] 2022-08-21 21:13
@geominorai all the tweets in #356 are now working - they were all deleted tweets 🙂 or if you're still seeing it in 3.0.0-beta1, please let me know. 

I think @kvnvallis might be seeing a different error, or the same error but caused by a different tweet.

**Comment by kvnvallis** [comment] 2022-08-21 21:23
Sorry, v3.0.0-beta1 works fine, the issue is resolved. I thought i had installed it but i was still using 2.16.3

**Comment by geominorai** [comment] 2022-08-21 22:05
I get an "App not installed" error when I try installing the beta, so I cannot test this. Uninstalling the old version first did not seem to help.

**Comment by jonjomckay** [comment] 2022-08-21 23:56
@geominorai @fusionneur that usually happens when the app is installed from a different source (e.g. F-Droid), as its signed with a different key. You'll need to uninstall the app, including from any other profiles (like a Work profile, or Shelter profile), then install it from GitHub. Or wait for the beta to come through to F-Droid in a few days.

I know it's annoying, but it's an Android limitation :(

**Comment by jonjomckay** [comment] 2022-08-21 23:57
Closing, as this appears fixed now.

**Closed by jonjomckay** 2022-08-21 23:57 UTC
Labels: bug, pending response

**Comment by geominorai** [comment] 2022-08-22 00:04
Thanks, it installed after I found and cleared the old versions out of all profiles. 

I can confirm the patch works on the previously mentioned Twitter comments!
