### ISSUE TITLE
[REQ] Mouse scrolling

### ISSUE THREAD

**Issue by IamDeepx** [jonjomckay/fritter#423] opened 2022-08-07 02:39 UTC
**Describe the problem that needs solving**
So for me the app is unusable due to it not having the left click and drag scrolling feature and the mouse scrolling is slow.
I'm using an android 4.4.2 TV box with a mouse.

**Describe the solution you'd like**
I would like to be able to scroll through fritter by left clicking and dragging or by being able to use mouse scrolling.

**Comment by jonjomckay** [comment] 2022-08-22 15:23
Closing as a duplicate of #261. Please follow that issue for updates!

**Closed by jonjomckay** 2022-08-22 15:23 UTC
Labels: enhancement
