### ISSUE TITLE
[REQ] Option to change font size

### ISSUE THREAD

**Issue by peter099** [jonjomckay/fritter#396] opened 2022-05-16 15:58 UTC
**Describe the problem that needs solving**
The text font is small on my phone and i want to increase it.

**Describe the solution you'd like**
Increasing the text font size will be useful feature.

**Comment by jonjomckay** [comment] 2022-08-22 15:36
Closing as a duplicate of #279. Please follow that issue for updates!

**Closed by jonjomckay** 2022-08-22 15:36 UTC
Labels: enhancement
