### ISSUE TITLE
[REQ] Be able to subscribe to a saved search

### ISSUE THREAD

**Issue by WeeBull** [jonjomckay/fritter#229] opened 2021-08-22 12:30 UTC
One thing I often have set up on tweetdeck is a saved search for a hashtag. For example, searching for #GridWeekCharts gives graphs of the electricity generation mix of the UK each week. Another use is getting all chatter around events. Although I can do the search in Fritter, I can't save it and have to enter the tag each time. 

_Feature 1._  Have a save search facility

Once we had that I'd like to be able to treat it like any other "subscription" and add it to groups so that posts that meet that search get mixed in with the timeline for that group.

_Feature 2._ Allow saved searches to be used in the same way as channel subscriptions.

**Comment by robna** [comment] 2021-10-11 13:15
I would really like to do exactly that! This is also similar / duplicate of #178

**Closed** 2022-09-23 12:56 UTC
Labels: enhancement
