### ISSUE TITLE
[BUG] No NSFW Tweets or Users!

### ISSUE THREAD

**Issue by notBradPitt** [jonjomckay/fritter#662] opened 2023-04-15 13:04 UTC
Same issue like what Nitter is facing. Seems like the freedom-loving Elon has removed access to NSFW accounts and tweets from anonymous API requests. The current workaround is to use the instance's login credentials which is then for all users like https://nitter.privacydev.net/. However, I think it'll be better if there was an option to switch this feature on and off and changing the credential, since it seems to slow down the response time and might get rate limited if everyone is using the same credentials.

**Comment by sargonzal** [comment] 2023-04-16 22:20
You getting snarky here Mr.? Freedom loving Elon? As opposed to actual communists that ran the company before and did what commies love to do which is to dissappear what/who they don't like.

**Comment by notBradPitt** [comment] 2023-04-17 03:34
> You getting snarky here Mr.? Freedom loving Elon? As opposed to actual communists that ran the company before and did what commies love to do which is to dissappear what/who they don't like.

Very funny. What positive changes has Elon made since he bought Twitter again?
Turned the verified badge into "I paid $8 for this badge". Lost 50 of its 100 top advertisers. Fired thousands of employees. Removed Trust and Safety department. Fired dozens more because they criticized him. Account bans on whoever made fun of him. Banned ElonJet after he explicitly stated that he wouldn't do so. And now he wants to use CCP's WeChat as Twitter's future blueprint, starting by merging Twitter into X Corp today?

Stop dickriding. Elon is the opposite of everything he stands for but of course, bootlickers like you just see him as whatever he says he is, instead of what he actually is. He's nothing but another rich man trying to make himself even richer and he can't do that when people are using API instead of a Twitter account which he can track. This is clearly the opposite of what he said he wanted to turn Twitter into, am I wrong for pointing that hipocrisy out?

If you want to be like Elon and contribute nothing, please get out of this issue. Nobody gives a shit about what you think of him. You're just a waste of time if you're not gonna help solve this issue

**Comment by nospace-here** [comment] 2023-04-22 06:56
> did what commies love to do which is to dissappear what/who they don't like.

With Elon unironically catering to the Chinese COMMUNIST Party by removing state-affiliation markers on their profile which they wanted gone, 

https://www.youtube.com/channel/UCgFP46yVT-GG4o1TgXn-04Q/community?lb=UgkxNHbEkHUjLXu0pLvN014HVAM09uXQLvqC

https://www.youtube.com/channel/UCgFP46yVT-GG4o1TgXn-04Q/community?lb=Ugkxj6JNSLWB2W96Ti_5igsotmvh9P7KayDp

it's a step-up.

**Comment by raniesantos** [comment] 2023-04-23 15:57
I'm subscribing to this issue. Please don't close it until a working update is actually published.

**Comment by ThoriumTextile** [comment] 2023-04-24 23:48
> > did what commies love to do which is to dissappear what/who they don't like.
> 
> With Elon unironically catering to the Chinese COMMUNIST Party by removing state-affiliation markers on their profile which they wanted gone,
> 
> https://www.youtube.com/channel/UCgFP46yVT-GG4o1TgXn-04Q/community?lb=UgkxNHbEkHUjLXu0pLvN014HVAM09uXQLvqC
> 
> https://www.youtube.com/channel/UCgFP46yVT-GG4o1TgXn-04Q/community?lb=Ugkxj6JNSLWB2W96Ti_5igsotmvh9P7KayDp
> 
> it's a step-up.

Can we please keep this on topic? This has nothing to do with Elon's affiliation, religious belief, what he ate for lunch or very poor decision making.

**Comment by jonjomckay** [comment] 2023-04-29 12:38
Closing as a duplicate of #658

**Closed by jonjomckay** 2023-04-29 12:38 UTC
Labels: bug

**Comment by lucasemmanuelferreiradearaujo** [comment] 2023-06-05 13:54
18
