### ISSUE TITLE
Show Profile status, joined dated, webaite and location

### ISSUE THREAD

**Issue by ghost** [jonjomckay/fritter#88] opened 2021-05-15 04:23 UTC
![Screenshot_20210515-094413696_1_1](https://user-images.githubusercontent.com/75672019/118347769-59ec9a00-b563-11eb-9aa2-71f104ee2101.jpg)

**Comment by jonjomckay** [comment] 2021-09-30 17:55
Closing as a duplicate of #223 (although this one came first, the reporter no longer has an account)

**Closed by jonjomckay** 2021-09-30 17:55 UTC
Labels: enhancement
