### ISSUE TITLE
Add login option

### ISSUE THREAD

**Issue by Erictheplague** [jonjomckay/fritter#459] opened 2022-09-02 04:19 UTC
I think a login option should be added on fritter because it's difficult seeing content you associate with without login into fritter

**Comment by Aga-C** [comment] 2022-09-02 07:41
https://github.com/jonjomckay/fritter/issues/105

**Comment by jonjomckay** [comment] 2022-09-21 20:54
Closing as a duplicate of the issues mentioned above - this isn't something Fritter will support.

Quoting from #105:

> Sorry, this doesn't match up with what Fritter is aiming for! Please see [here](https://github.com/jonjomckay/fritter/discussions/75#discussioncomment-725584) for an answer I gave on where I see Fritter fitting in. There's also some more information on [fritter.cc](https://fritter.cc) regarding privacy Fritter's other ideals.

> As mentioned by @eredrolo, Twidere is a decent alternative if you want to use an account.

**Closed by jonjomckay** 2022-09-21 20:54 UTC
Labels: enhancement
