### ISSUE TITLE
Unable to load the group/list subscriptions 

### ISSUE THREAD

**Issue by wongfeihung1984** [jonjomckay/fritter#175] opened 2021-06-21 06:58 UTC
Describe the bug
When opening the app, shown this error message. Subscriptions and feeds can'tbe displayed. Though I can still look at trends and saved tweets.

To Reproduce
1. open the app
2. shown this error

Screenshots
attached
![Fritter bug](Fritter bug https://imgur.com/gallery/Cg2RLYe)

Device
v 2.10.0
Samsung GalaxyS9+ 
Android 10

**Comment by jonjomckay** [comment] 2021-06-21 09:22
I think you can work around this by tapping the refresh button, but I'm not 100% what's actually causing this - it's another thing I can't reproduce (or find any useful reference to) so I think it's also something different in SQLite between devices.

I'm going to keep trying to find out what's causing this this week.

**Comment by wongfeihung1984** [comment] 2021-06-21 10:11
Thank you. Tapping the refresh button did the trick.

**Comment by jonjomckay** [comment] 2021-06-21 17:03
It looks like this was fixed in v2.11.2 already, so closing for now.

I left you a reply on #170 that should allow you to install the updated version, as F-Droid still hasn't built it yet!

**Closed by jonjomckay** 2021-06-21 17:03 UTC
Labels: bug
