### ISSUE TITLE
Group "All" doesn't show all tweets

### ISSUE THREAD

**Issue by desertproject** [jonjomckay/fritter#145] opened 2021-06-10 15:43 UTC
Hi! In addition to the default group **All**, I've created two more groups. When I'm in the **All** group, only tweets from one of the groups I've created myself are show. The expected behavior is that the group **All** shows tweets from all my subscriptions, being them members of a group or not.

- Android: `8.0.0`
- Fritter: `2.8.0`

Many thanks!

**Comment by jonjomckay** [comment] 2021-06-11 16:19
This might be #68 rearing its head again - there's an issue with Fritter's use of the Twitter Search API, where the API doesn't actually return all tweets from the user in the last 7 days. Does that sound like it could be the same issue?

**Comment by desertproject** [comment] 2021-06-11 22:57
Hmm, I'm not sure. I'm getting a reasonable number of new tweets while browsing **All**, but only from "Group 1", not a single one from "Group 2". _Group 1_ has 9 subscriptions and _Group 2_ has 8. Browsing the feed of _Group 2_ I again can get a reasonable number of new tweets, which is strange.

_Group 1_ comes first in dictionary order. Maybe _Group 1_ consumes all the API first and lefts no room to _Group 2_?

**Comment by DocSniper** [comment] 2021-06-12 16:08
I also have a problem that could be exactly this one. 
However, it seems that some users are displayed in Feed and All, but other users are completely missing.

**Comment by jonjomckay** [comment] 2021-06-12 18:09
Thanks both for your responses. Would either of you be able to export and email me your list of subscriptions and groups so I can try and reproduce in my debugger? The email is support@fritter.cc.

Please let me know if you'd prefer to keep that info private and we can try and find a different way to get a reproduction!

**Comment by login22rvp** [comment] 2021-06-13 04:12
I think may be having a load more button will help. Tht way certain numbers of tweets can be loaded in 1st load and then after clicking on load more additional next round of tweets from subscribers can loaded.

I also noticed the issue mentioned here.
I am assuming the tweets are loaded chronologically, but sometime even after a tweet being shown in individual subscriber list, it's not shown when the all feed is loaded.

**Comment by desertproject** [comment] 2021-06-21 20:59
I can't say for the others but now In v2.11.2 I'm seeing a more evenly distribution of tweets. Tweets from all groups started to show up in "Feed" and "All"

**Comment by jonjomckay** [comment] 2021-06-25 13:49
@desertproject I think that might be due to 2171fc386b349c4be4797a8d92a1467ca245cf79. I was hoping it would help somewhat.

Can anyone else confirm if things are better/fixed since v2.11.2?

**Comment by DocSniper** [comment] 2021-06-25 14:00
I can confirm that it is much better with v2.11.2, but I have not yet tested in depth whether the problem is completely fixed or not.

**Comment by warren-ru** [comment] 2021-08-11 04:25
A problem is not the same, but looks similar.
I can't the user's retweets even when toggle the option in the feed settings. I can see his own tweets only.

**Comment by jonjomckay** [comment] 2022-09-23 13:32
I think this is now fixed in the latest development build. Are you able to try it and report back?

**Comment by jonjomckay** [comment] 2023-04-29 14:27
Closing as the feed has now been removed, due to Twitter blocking access permanently. Please see https://github.com/jonjomckay/fritter/issues/668#issuecomment-1528784190

**Closed by jonjomckay** 2023-04-29 14:27 UTC
Labels: pending response
