### ISSUE TITLE
[BUG] v2.11.0 crashes at first launch 

### ISSUE THREAD

**Issue by frais64** [jonjomckay/fritter#165] opened 2021-06-18 20:01 UTC
**Describe the bug**
Fritter v2.11.0 crashes at first launch (never used the app before).
I tested the F-Droid version and it works fine. 

**To Reproduce**
1. Launch the app for the first time

**Screenshots**
![Screenshot_20210618-214856_Fritter](https://user-images.githubusercontent.com/70917976/122610763-b580da80-d06f-11eb-9a6e-7079e893fe98.jpg)

**Device**
Samsung A51, Android 11, Fritter v2.11.0

**Comment by desertproject** [comment] 2021-06-18 20:16
This also happens after updating from v2.10.0

**Comment by jonjomckay** [comment] 2021-06-18 20:30
Hmm, I can't replicate this but it looks like it's something different in SQLite between our devices: https://stackoverflow.com/questions/6268064/alter-table-drop-column-syntax-error-using-sqlite

I'll see if there's another way to fix this and push a fix ASAP

**Comment by RickyM7** [comment] 2021-06-18 20:38
Same here!

- Device: Redmi Note 4 (MIUI 11 - Android 7.0)

**Comment by jonjomckay** [comment] 2021-06-18 20:53
I've pushed what could be a fix, but as I'm unable to reproduce it, I can't test it 😢 

Would someone on this thread please be able to download the APK, try it out, and report back here? You can download it here: https://github.com/jonjomckay/fritter/runs/2861680516

Thank you!

**Comment by WindHun7er** [comment] 2021-06-18 20:59
> Would someone on this thread please be able to download the APK, try it out, and report back here? You can download it here: https://github.com/jonjomckay/fritter/runs/2861680516

Tried it. Bug fixed on my side. Everything works like a charm !

**Comment by frais64** [comment] 2021-06-18 21:03
> Would someone on this thread please be able to download the APK, try it out, and report back here? You can download it here: https://github.com/jonjomckay/fritter/runs/2861680516

Works fine for me as well!

**Comment by Fs00** [comment] 2021-06-18 21:06
I tested the hotfix but didn't work for me. This time the error was a bit different though. I will post the screenshot as soon as I can.

I have cleanly installed the app on my Sony Z3 Compact, LineageOS 17.1.

**Comment by desertproject** [comment] 2021-06-18 21:14
Sadly it didn't worked for me as well. But before trying the hotfix I tried to install back v2.10.0 and it was not possible, then I installed back v2.11.0. Maybe those actions interfered.

**Comment by jonjomckay** [comment] 2021-06-18 21:14
@Fs00 @desertproject  I _think_ I fixed your secondary issues in 80332186be26fc55a1924547a2b98fb7dbd9926d - I noticed a couple more slightly different bug reports come in so hopped on that one too (thanks to those who reported!). I've tagged v2.11.1 so I'll close this for now, but please re-open if the fix doesn't work for you! Thanks all for your patience and understanding - open source rules 😄

**Closed by jonjomckay** 2021-06-18 21:14 UTC
Labels: bug

**Comment by jonjomckay** [comment] 2021-06-18 21:18
@Fs00 I've just opened an issue to make the error text selectable - #166

**Comment by RickyM7** [comment] 2021-06-18 21:23
I just tested the v2.11.1 and the bug has been fixed, thank you!

**Comment by desertproject** [comment] 2021-06-18 21:23
> @Fs00 @desertproject I _think_ I fixed your secondary issues in [8033218](https://github.com/jonjomckay/fritter/commit/80332186be26fc55a1924547a2b98fb7dbd9926d) - I noticed a couple more slightly different bug reports come in so hopped on that one too (thanks to those who reported!). I've tagged v2.11.1 so I'll close this for now, but please re-open if the fix doesn't work for you! Thanks all for your patience and understanding - open source rules smile

Thanks! That worked! I just needed to reload the subscription list.

**Comment by Fs00** [comment] 2021-06-18 21:24
Thank you! Can confirm that 2.11.1 fixed this issue on my end :D
