### ISSUE TITLE
Twitter search results fail ( BUG)

### ISSUE THREAD

**Issue by rsssxd** [jonjomckay/fritter#476] opened 2022-09-06 21:33 UTC
https://user-images.githubusercontent.com/60405617/188744914-2e5061db-dba9-4bcd-8cdd-8d0f3691a94e.mp4

**Comment by rsssxd** [comment] 2022-09-06 21:34
Actions new versions

**Comment by Aga-C** [comment] 2022-09-07 06:07
It's the same as in https://github.com/jonjomckay/fritter/issues/472.

**Comment by jonjomckay** [comment] 2022-09-09 11:15
Closing as a duplicate of #472.

**Closed by jonjomckay** 2022-09-09 11:15 UTC
Labels: bug
