### ISSUE TITLE
[BUG] Unable to load feeds

### ISSUE THREAD

**Issue by Samuelinox** [jonjomckay/fritter#680] opened 2023-04-27 07:26 UTC
**Describe the bug**
Catastrophic failure in feeds

**To Reproduce**
1. Go to feeds
3. See error

**Screenshots**
![Screenshot_2023-04-27-09-22-52-07_436fee948e6915f72a63614ccc1d2985.jpg](https://user-images.githubusercontent.com/63791402/234789446-14fcea84-90b7-41a2-87c9-6464cecd1c59.jpg)

**Device**
Device: OPPO Reno 8 Pro
OS version: Color OS 13.0 (CPH2357_11_C.28)
Device Locale: Italian
Fritter version: v3.0.0-beta7+300000957

**Comment by eye-writ** [comment] 2023-04-27 08:39
Same here. A different error message to the one previously logged and clearing the app data no longer fixes it.

**Comment by mix1607** [comment] 2023-04-27 08:52
Same bug here, was happening on the last stable build as well then I upgraded to beta and it worked fine untill I loaded my Twitter account into the app.

**Comment by MikaelaMuller** [comment] 2023-04-27 14:50
Same here v3.0.0-beta7+300001957

**Comment by jonjomckay** [comment] 2023-04-29 12:32
Closing as a duplicate of #668

**Closed by jonjomckay** 2023-04-29 12:32 UTC
Labels: bug
