### ISSUE TITLE
[REQ] Please support http/socks proxy

### ISSUE THREAD

**Issue by rustforfuture** [jonjomckay/fritter#280] opened 2021-11-04 20:04 UTC
**Describe the problem that needs solving**
A clear description of what the problem is. E.g. I'm always frustrated when [...]

Please support http/socks proxy for those reigns that blocked the website or for other use cases (networks that need it)

**Describe the solution you'd like**
A clear description of what you want to happen.

Please support http/socks proxy for those reigns that blocked the website or for other use cases (networks that need it)

Thank you very much

**Comment by givena** [comment] 2021-11-21 17:23
i believe you can also use orbot

**Comment by jonjomckay** [comment] 2022-09-21 20:58
Closing as a duplicate of #191.

**Closed by jonjomckay** 2022-09-21 20:58 UTC
Labels: duplicate, enhancement
