### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by mukyumukyun** [jonjomckay/fritter#672] opened 2023-04-25 09:38 UTC
![Screenshot_20230425-162330_Fritter_1](https://user-images.githubusercontent.com/30382926/234234893-a8082c4f-1ac1-44e8-8237-fda641e185cb.png)
seems like there's a lot of problem like this (in the latest stable build and latest beta version of the app) that I've experienced, that I assumed other users experienced too

it seems that the trigger is that the filter for the feed is both "include replies" and "include retweets" being checked, and sometimes even when I don't checked both of those filter, it still like the top screenshot when I refresh my feed with a slide down gesture (but when I refresh with the available function in the top icon, it rarely even breaks unless both of the filters being checked), so I suggest to just get the option to disable down gesture to refresh and disable it as the default option

**Comment by s0racat** [comment] 2023-04-25 09:41
#668

**Comment by jonjomckay** [comment] 2023-04-29 12:33
Closing as a duplicate of #668

**Closed by jonjomckay** 2023-04-29 12:33 UTC
Labels: bug
