### ISSUE TITLE
[BUG] Swipe up on pictures is doing the same as Android "Back" button ! 

### ISSUE THREAD

**Issue by GLLM** [jonjomckay/fritter#497] opened 2022-09-11 17:52 UTC
Hello,

I'm using v3.0.0-beta3, I'm not logged in into any twitter account (dont have one), I just have subscriptions.

Swipe up on picture within a tweet is doing the same as the "Back" button from Android.
It's a massive P.I.T.A because while you thought you were of scrolling on the thread, you actually swipe up on a picture. And then it's doing a "back" press and you are exited, unwillingly, out of your thread ... so you need to enter it again, scroll a long time until you find the one tweet you were reading.

In fact, when doing some in your stream, you can even get a black screen (fritter is stuck) when swiping up (on a picture, by bad luck) on the picture of a tweet ... probably because fritter does not know what to do !

Test case
1. open a long thread (e.g. https://twitter.com/kamilkazani/status/1505247886908424195)
2. scroll along it ... the one given is lengthy
3. by swiping up (finger goes from screen bottom towards screen top), there are chances that you do it on a picture. Nothing unusual.
4. What is unexpected and very bothering is that, when doing so, you are, against your will, exited from your thread because fritter does as is as you press android back button !

Thanks
GLLM

**Comment by jonjomckay** [comment] 2022-09-11 22:49
Closing as a duplicate of #477, but thank you for the detailed report!

**Closed by jonjomckay** 2022-09-11 22:49 UTC
Labels: bug
