### ISSUE TITLE
[BUG] Images in full screen are cropped vertically if taller than device height

### ISSUE THREAD

**Issue by V13Axel** [jonjomckay/fritter#451] opened 2022-08-28 11:33 UTC
**Describe the bug**
Images taller than the device aspect ratio are cropped vertically.

**To Reproduce**
1. Have a device with a 4:3 aspect ratio
2. Open any image taller than that
3. Be unable to see the whole image

**Screenshots**
Here you can see the text toward the bottom of this image:
![Screenshot_20220828-071729](https://user-images.githubusercontent.com/2779682/187071728-63805e80-315f-409b-9ec1-ab4e528fcdcc.png)

Here you cannot:
![Screenshot_20220828-071743](https://user-images.githubusercontent.com/2779682/187071749-92e01e92-8ea3-4f41-a6c5-c95f7ce1347d.png)

**Device**
Microsoft Surface Duo 2, Android 11, any version of Fritter up to and including 3.0.0-beta1.

**Comment by jonjomckay** [comment] 2022-08-28 18:21
This is a duplicate of #390, but is fixed in v3.0.0, and is available in the latest CI build 🙂

**Closed by jonjomckay** 2022-08-28 18:21 UTC
Labels: bug

**Comment by V13Axel** [comment] 2022-08-28 19:08
Whoops! Sorry, I tried searching existing issues and came up short.
