### ISSUE TITLE
Refresh feed

### ISSUE THREAD

**Issue by ghost** [jonjomckay/fritter#202] opened 2021-07-22 08:16 UTC
Please implement a swipe down to refresh feature for Feed tab like in a browser

Like this
![IMG_20210722_134528](https://user-images.githubusercontent.com/71541566/126608766-3089d85b-3837-4ded-9000-3b9c7cbf9800.jpg)

**Comment by jonjomckay** [comment] 2021-08-06 15:13
Closing as a duplicate of #100. This will be in the next version (v2.14.0)

**Closed by jonjomckay** 2021-08-06 15:13 UTC
Labels: enhancement
