### ISSUE TITLE
[BUG] App freeze when jumping in video

### ISSUE THREAD

**Issue by Alcidauk** [jonjomckay/fritter#172] opened 2021-06-19 22:08 UTC
**Describe the bug**
After starting video play, if I try to jump at another timestamp, the whole app freeze. I then need to kill it.

**To Reproduce**
1. Go to a tweet with embedded video
2. Start playing video
3. Click on the timeline.

**Screenshots**
I don't think a screen will help but I can provide ond if needed.

**Device**
Moto Z with GSF, android 10 (lineageOs), fritter 2.10.0.

Nota: a huge thanks for this amazing app. It's really much simplier to use this app instead of twitter website !

**Comment by JJFlash-IT** [comment] 2021-06-19 22:10
Aaasss

**Comment by JJFlash-IT** [comment] 2021-06-19 22:17
Hey there,
just wanted to add that I'm having the same problem as well. I didn't try to seek to any particular point in any video, but I experience this: after I watched the video, if I want to see it again and tap the "repeat" icon, the app completely freezes and I have to force-close it to be able to see it again.
I'm using a Samsung Galaxy A10, Android version 10, Fritter version 2.11.2.

Thank you so much for your app, I absolutely love the NewPipe approach!

**Comment by jonjomckay** [comment] 2021-06-21 17:06
I've only been able to reproduce this once, and at a time where I wasn't at my computer to debug 😢.

But that being said, this is a duplicate of #161 so I'll close this for now, and copy your comments over. Please continue any discussion over there!

**Closed by jonjomckay** 2021-06-21 17:06 UTC
Labels: bug

**Comment by jonjomckay** [comment] 2021-06-23 19:38
Oops, this is actually a duplicate of #147 - sorry!
