### ISSUE TITLE
[BUG] Image control is working when scrolling feed

### ISSUE THREAD

**Issue by LeducBastien** [jonjomckay/fritter#516] opened 2022-09-23 07:35 UTC
**Description**
Image control works when scrolling the feed, when it should not.
When you scroll your feed, whether from a search or your feed, if you encounter an image and you scroll on it, the image itself will move up or down depending on your scroll, and you'll be put back on your research quitting the current feed, or to a black screen.
Image control should only work when you first tap it.

**Step to reproduce the bug**
1. Search for a random feed
2. Scroll the feed until you find an image
3. Make the scroll movement on the image, the image is reacting to your scroll
4. The app makes you go back to your previous research and quits your feed.

 **ALT**
1. Scroll your feed
2. Scroll on an image
3. The image react to your scroll and move on itself
4. Release the input
5. You're brought to an empty void

**Occurrence**
I can only reproduce it sometimes, not all the time.

**Device**
Xperia 10
Android 10
(Latest beta version of 23/09/2022 as the app shows me "v+" version)

**Screenshot**
Before:
![Screenshot_20220923-092210.png](https://user-images.githubusercontent.com/25571639/191912034-58dcf266-61cf-47d5-8387-52f57b2e2d58.png)

Scrolling on the image:
![Screenshot_20220923-092203.png](https://user-images.githubusercontent.com/25571639/191912061-c8df1a1f-9685-4d26-9ac4-5ac9ac17c5f9.png)

After releasing input when searching:
![Screenshot_20220923-092759.png](https://user-images.githubusercontent.com/25571639/191912115-cf57ff39-a977-4083-b89a-4334ed21a442.png)

After releasing input when scrolling your feed:
![Screenshot_20220923-092723.png](https://user-images.githubusercontent.com/25571639/191912179-5cc71ac1-421c-422a-8a8e-30a02190e9f2.png)

**Comment by Aga-C** [comment] 2022-09-23 08:51
It's the same as https://github.com/jonjomckay/fritter/issues/514.

**Comment by jonjomckay** [comment] 2022-09-25 20:58
Closing as a duplicate of #477. The latest beta version contains this fix if you'd like to try it!

**Closed by jonjomckay** 2022-09-25 20:58 UTC
Labels: bug

**Comment by LeducBastien** [comment] 2022-09-28 06:11
Sorry to reopen the case, but I would like to confirm I was not able to reproduce the bug.

Instead, the scroll sometimes stops and only resume when not clicking the image.
Otherwise the user experience is much better now!
