### ISSUE TITLE
[BUG] The clipboard is being used when browsing a feed

### ISSUE THREAD

**Issue by McBaumwolle** [jonjomckay/fritter#238] opened 2021-09-21 14:58 UTC
> Please make sure you've tried the [latest version](https://github.com/jonjomckay/fritter/releases) of Fritter first, as the F-Droid version is sometimes out of date!

**Describe the bug**
Fritter reads the clipboard, or at least Android 12 says so. 

**To Reproduce**
1. Open Fritter on Android 12
2. Tap "Feed"

**Screenshots**
![image](https://user-images.githubusercontent.com/67203883/134194458-cce66999-a1b3-432b-9d09-4dda91625675.png)

**Device**
Pixel 5
Android 12 Beta (SPB5.210812.002)
App Version v2.14.0+20210910

**Comment by jonjomckay** [comment] 2021-09-30 18:04
This looks like it's caused by [some behaviour in Flutter itself](https://github.com/flutter/flutter/pull/87678), and the PR has been merged in so it should be available in the next version of Flutter. I'll upgrade Fritter once that arrives, and this should get fixed automatically!

**Comment by jonjomckay** [comment] 2022-01-13 19:06
Just to keep this thread up-to-date - I've updated to the latest version of Flutter (v2.8.1) and this still occurs, so it looks like there's still some more work for the Flutter team to do, despite the above PR being merged in...

**Closed** 2024-05-04 06:55 UTC
Labels: bug
