### ISSUE TITLE
[BUG] Crash at startup

### ISSUE THREAD

**Issue by aricamblor** [jonjomckay/fritter#598] opened 2022-12-20 12:28 UTC
**Describe the bug**
When I open the app it crashes with error message: "Something broke in Fritter. RangeError (length): Invalid value: Not in inclusive range 0..3: -1"

 This happened after updating to latest version 2.16.4 with F-Droid

**To Reproduce**
1. Open app.

**Screenshots**

**Device**
Pixel 3a with Android 12

**Comment by amadoumx** [comment] 2022-12-20 23:15
Same Here.

**Comment by nhfo** [comment] 2022-12-21 08:24
I wonder if this is related to version and 3.x beta builds.
3.0.0-beta5 version code is 202211262
2.16.4 version  code is 202212092

IIUC android will allow installing 2.16.4 over 3.0.0-beta5. I think this is what happened for me. Is there some incompatibilities in app data that would cause app version 2.16.4 to crash like this?

**Comment by Aga-C** [comment] 2022-12-21 08:28
The newest version is [v3.0.0-beta6](https://github.com/jonjomckay/fritter/releases/tag/v3.0.0-beta6).

**Comment by nhfo** [comment] 2022-12-21 08:52
> The newest version is [v3.0.0-beta6](https://github.com/jonjomckay/fritter/releases/tag/v3.0.0-beta6).

@Aga-C  Is it just FYI? Or are you implying something?

**Comment by nhfo** [comment] 2022-12-21 09:46
@Aga-C while I understand value of keeping noise ratio low, I would argue that templates are guidelines at best and should not be enforced in absolute terms. 

What template dictates, is not practical, at least always. For example if someone did not create a backup, did an upgrade and then app start crashing during startup, in that case testing the latest version would mean loosing the data if that require app to be uninstalled first (when changing build source github vs fdroid). Also issue may not surface on a clean install. 

Now maybe following is not the root cause of this issue, that still needs to be determined. However here is a real problem -- the disconnect between textual version name and version code. While version name is more prominently shown to user, it is the version code, that determines if installing apk would be upgrade or downgrade. 

As I pointed out above, 2.16.4 has greater version code than that of version 3.0.0-beta5. Clearly version code should not be based on release date (assuming it is that). Version code should ensure that app from a beta/next/development code line should have greater version code from stable code line, so that one  can not upgrade to incompatible version.

**Comment by volteret4** [comment] 2023-01-02 16:19
I tried to update to beta 3.0.0-beta6 whutout succes.  I ll wait to it in fdroid.

**Comment by ezx-code** [comment] 2023-01-13 07:58
Hello,
Same problem here... With 2.16.4.202212092
( Beta3? Seems to be last version avalaible..)
I can downgrade or upgrade neither from store nor f-droid.. it try but fails in the end.
Is there some place to download a beta6 apk?
Regards.
Fred

**Comment by ezx-code** [comment] 2023-01-13 08:16
I found the beta6 release but it won't install ... Installer tells it's in conflict with another app installed..

**Comment by jonjomckay** [comment] 2023-01-13 14:16
This is caused by installing v2.16.4 over the v3.0.0 betas, which isn't supported. Only the latest stable version in the v2 series (currently v2.16.4) is marked as the suggested version in F-Droid, so please take note of that when manually upgrading! The v3 series will be marked as suggested once it's released as a final, stable version.

**Closed as completed by jonjomckay** 2023-01-13 14:16 UTC
Labels: bug

**Comment by ezx-code** [comment] 2023-01-14 09:08
Hello 
Ok then i might have done this dangerous 'downgrade'.. 
Do i have a way to backup my datas? 
Thanks you and best regards.
