### ISSUE TITLE
[REQ] A way to only view media posts in your feed

### ISSUE THREAD

**Issue by Walrusz** [jonjomckay/fritter#597] opened 2022-12-20 11:14 UTC
I follow a lot of artists that I have a separate group for, but I'm only interested in seeing their media posts and not text-only tweets.

Would it be possible to have a toggle/feed to only show mefia posts in your feed, similar to the media tab on individual profiles?

**Comment by Aga-C** [comment] 2022-12-21 08:34
It's a duplicate of https://github.com/jonjomckay/fritter/issues/330.

**Comment by jonjomckay** [comment] 2023-04-29 14:28
Closing as the feed has now been removed, due to Twitter blocking access permanently. Please see https://github.com/jonjomckay/fritter/issues/668#issuecomment-1528784190

**Closed by jonjomckay** 2023-04-29 14:28 UTC
Labels: enhancement
