### ISSUE TITLE
[BUG] scrolling problem

### ISSUE THREAD

**Issue by jithinjames916** [jonjomckay/fritter#514] opened 2022-09-21 14:33 UTC
**Describe the bug**
When u socrool throu tweets, sometime picture react like the been selected and u trying to pull up to go back, and move to last visited page

**To Reproduce**
1. Go to a page full picture post
2. And scroll
3. In some time you move back to hoome screen

Also while scroling there is a high chance of accidentally pulling to the right(tweets&replies)
Which  when pullbacked refresh the page making 
Me starting to scroll.from the top again

**Device**
Nokia 3.2, Android 11
Fritter v 3.0.0-beta3

**Comment by jonjomckay** [comment] 2022-09-21 20:52
This is a duplicate of #477 which has now been fixed, and will go out in the next beta release. You can also download the latest development build from GitHub CI.

**Closed by jonjomckay** 2022-09-21 20:52 UTC
Labels: bug
