### ISSUE TITLE
[REQ] Only show replies between users you follow

### ISSUE THREAD

**Issue by articnova** [jonjomckay/fritter#636] opened 2023-02-04 15:42 UTC
**Describe the problem that needs solving**
Currently the timeline shows all replies that the users I follow make to other twitter users

**Describe the solution you'd like**
I'd like the option to hide replies to users I don't follow. I.e. Only show replies between users on my followed list

**Comment by Cripy-P** [comment] 2023-02-15 16:47
I remember seeing this as a problem some time ago, and it's the one thing that keeps me from using this application as my primary. It doesn't change if I deactivate the 'Include replies' option

**Comment by jonjomckay** [comment] 2023-02-15 16:54
IIRC, this is already fixed. Is this happening on the latest beta version?

If you're still running the latest stable (v2.16.x) please try the beta and let me know if you're still seeing the issue.

**Comment by articnova** [comment] 2023-02-15 18:16
Yes it is happening for me on v2.16.4+202212092. 

Sorry I may be missing it but is this an option in the settings?

**Comment by Cripy-P** [comment] 2023-02-15 19:35
It worked for me, seems to work as intended, thank you!
@articnova go to releases and download the last beta (v3.0.0-beta6): https://github.com/jonjomckay/fritter/releases 

Finally, is there an estimated date for this to make it to stable?

**Comment by articnova** [comment] 2023-02-15 20:31
Okay I downloaded the beta and it did remove the replies from the feed when unticking "include replies".

I suppose the change I'm requesting is that I would like to see replies but only between users on my subscription. e.g. If someone tweets on their own tweet creating a thread, I'd like to see that. However if they replied to someone I don't follow then I do not want to see that.

If that change is possible that would be great

**Comment by jonjomckay** [comment] 2023-04-29 14:30
Closing as the feed has now been removed, due to Twitter blocking access permanently. Please see https://github.com/jonjomckay/fritter/issues/668#issuecomment-1528784190

**Closed by jonjomckay** 2023-04-29 14:30 UTC
Labels: enhancement, pending response
