### ISSUE TITLE
Catastrophic failure since yesterday when you search for Rahul Gandhi[BUG]

### ISSUE THREAD

**Issue by bharatbhatt762** [jonjomckay/fritter#664] opened 2023-04-22 06:14 UTC
![Screenshot_20230422-114131](https://user-images.githubusercontent.com/38124293/233766203-fbf306c1-bde7-41fc-9d4c-6d6696f83072.png)
> Please make sure you've tried the [latest version](https://github.com/jonjomckay/fritter/releases) of Fritter first, as the F-Droid version is sometimes out of date!

**Describe the bug**
A clear description of what the bug is.

**To Reproduce**
3. See error

**Screenshots**

**Device**
Your device model, OS version, device locale/language and Fritter version. Please supply the actual
version of Fritter being used, and **do not** just write "latest version" or similar, as this
changes constantly.
#

**Comment by TheHCJ** [comment] 2023-04-23 19:34
This happens no matter what the search term is. I am working on a fix!

**Comment by bharatbhatt762** [comment] 2023-04-24 09:12
Hi

Don't know if this helps,
Twitter changed their API,  Nitter seems to have resolved this issue.

Best
Bharat

⁣Get TypeApp for Android ​

**Comment by jonjomckay** [comment] 2023-04-29 12:38
Closing as a duplicate of #669

**Closed by jonjomckay** 2023-04-29 12:38 UTC
Labels: bug
