### ISSUE TITLE
Replying the video Freezes the app

### ISSUE THREAD

**Issue by login22rvp** [jonjomckay/fritter#152] opened 2021-06-15 02:10 UTC
I am on latest version. Whenever i reply the video the overall app freezes. 

PS: superb development done.. Lots of new intresting and intuitive features.

**Comment by login22rvp** [comment] 2021-06-15 02:11
Replay*

**Comment by selurvedu** [comment] 2021-06-18 11:51
Same here.

**Comment by selurvedu** [comment] 2021-06-18 11:52
Probably the same bug as in #147.

**Comment by jonjomckay** [comment] 2021-06-23 20:07
This is a duplicate of #147, so I'll close this ticket for now. Please follow the other issue for updates!

**Closed by jonjomckay** 2021-06-23 20:07 UTC
